version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12 
  build:
    commands:
      - echo "Build Started..."
      - npm --prefix ./myfunction install ./myfunction
  post_build:
    commands:
      - echo "Cloudformation Started..."
      - aws cloudformation package --template-file update-status.yaml --s3-bucket githubtolambdabucket --output-template-file output.yaml
      - aws cloudformation deploy --template-file /codebuild/output/**/src/github.com/pillupriya/github-to-lambda-demo/output.yaml --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --stack-name myStackNameDemo --tags Key1=Value1 Key2=Value2 --role-arn arn:aws:iam::286367274205:role/service-role/agnes
      - echo "DONE!!"
