version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Build started on `date`
      - npm --prefix ./myfunction install ./myfunction
  post_build:
    commands:
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'