version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Build started on `date`
      - npm --prefix ./myfunction install ./myfunction
  post_build:
    commands:
      - pwd
      - ls -al
      - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://code-builds-on-qa/myfunction_QA
artifacts:
  files:
    - '**/*'
