version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12 
  build:
    commands:
      - echo "Build Started..."
      - find . -maxdepth  2 -name package.json -execdir npm i \
  post_build:
    commands:
      - echo "Cloudformation Started..."
      - aws cloudformation package --template-file update-status.yaml --s3-bucket githubtolambdabucket --output-template-file output.yaml
      - aws cloudformation deploy --template-file .\output.yaml --capabilities CAPABILITY_NAMED_IAM --stack-name myStackNameDemo
      # - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://function.zip
      - echo "DONE!!"